apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management-container
        image: rweek7.azurecr.io/inventory-management:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://week7_8x98_user:SZkfJDgPZLMW9E3ig1M4Q9ABIPhKwNAk@dpg-crvq98rtq21c738oqgr0-a.oregon-postgres.render.com/week7_8x98"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
